<?php
require_once 'func.php';

$_GET['id'] = (int) $_GET['id'];

$q = "SELECT name FROM threads WHERE id = {$_GET['id']}";
$res = db_query($q);
$patch = mysql_fetch_assoc($res)


?>
<!DOCTYPE html>
<html>
<head>
	<title>LibreOffice Patch Viewer</title>
	<link rel="stylesheet" href="assets/style.css">
</head>
<body>
<div id="head">
	<h1>LibreOffice Patch Viewer</h1>
</div>
<div id="body">
	
	
	<?php
	echo '<h2>', html($patch['name']), '</h2>';
	?>
	
	
	<?php
	$q = "SELECT attachments.name, attachments.url
		FROM attachments
		INNER JOIN messages ON attachments.message_id = messages.id
		WHERE messages.thread_id = {$_GET['id']}
		ORDER BY attachments.id ASC";
	$res = db_query($q);
	if (mysql_num_rows($res) == 0) {
		echo '<p>No valid attachments found :(</p>';
	} else {
		echo '<table>';
		echo '<tr><th>Name</th><th>URL</th><th>Quick-apply</th></tr>';
		while ($row = mysql_fetch_assoc($res)) {
			echo '<tr>';
			echo '<td>', html($row['name']), '</td>';
			echo '<td><a href="', html($row['url']), '">Download</a></td>';
			echo '<td class="quickapply">wget -O - ', html($row['url']), ' | git am</td>';
			echo '</tr>';
		}
		echo '</table>';
	}
	?>
	
	<p>&nbsp;</p>
	
	<?php
	$q = "SELECT subject, body, added FROM messages WHERE thread_id = {$_GET['id']} ORDER BY added ASC";
	$res = db_query($q);
	
	while ($row = mysql_fetch_assoc($res)) {
		echo '<div class="email">';
		echo '  <p class="added">', html($row['added']), '</p>';
		echo '  <h3>', html($row['subject']), '</h3>';
		echo '  <pre>', html(trim($row['body'])), '</pre>';
		echo '</div>';
	}
	?>
	
	
</div>
<div id="foot">
	<p>Generated by LibreOffice Patch Viewer v0.1</p>
</div>
</body>
</html>
